config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]

  resources :foods, except: [:update]
  resources :recipes, except: [:update] do
    resources :foods, only: [:new, :create, :destroy]
    resources :recipe_foods, only: [:new, :create, :destroy]
    patch 'toggle_public', on: :member
  end

  resources :public_recipes, except: [:update]

  resources :general_shopping_lists, only: [:index]

  root 'public_recipes#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'recipe_id'
  has_many :foods, through: :recipe_foods

  accepts_nested_attributes_for :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  layout 'standard'
  before_action :authenticate_user!

  def index
    @user = current_user
    @recipes = @user.recipes
  end

  def show
    @user = current_user
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @foods = current_user.foods
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_to @recipe, notice: 'Recipe public status updated.'
  end

  def create
    @recipe = Recipe.new(recipe_params.except(:food_quantities))
    @recipe.user = current_user

    if @recipe.save
      food_quantities = recipe_params[:food_quantities]
      food_quantities&.each do |food_id, quantity|
        # Process each food quantity as needed
        @recipe.recipe_foods.create(food_id:, quantity: quantity.to_i, recipe_id: @recipe.id) unless quantity.to_i < 1
      end
      redirect_to recipes_path
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    # destroy all recipe_foods
    @recipe.recipe_foods&.destroy_all

    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, food_quantities: {})
  end
end

app/views/recipes/index.html.erb
<%= render 'layouts/header' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<h1 class='header-title'>List of all recipes of <%= @user.name %></h1>
<h2><%= link_to 'Add Recipe', new_recipe_path %></h2>

<% if @recipes.empty? %>
  <h3 class='header-title'>No recipes found</h3>
<% else %>
  <% @recipes.each do |recipe| %>
    <div class='container-md recipe-container border border-dark'>
      <div class='recipe_name'>
        <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
        <% if can?(:destroy, recipe) %>
          <%= form_with(model: recipe, method: :delete, url: recipe_path(recipe)) do |form| %>
            <%= form.submit 'Delete', class: 'btn btn-danger' %>
          <% end %>
        <% end %>
      </div>
      <div><%= recipe.description %></div>
    </div>
  <% end %>
<% end %>

app/views/recipes/new.html.erb
<h2 class='header-title'>New Recipe</h2>

<%= form_with(model: @recipe, url: recipes_path, method: :post) do |f| %>
  <div class="field mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= f.label :preparation_time, class: 'form-label' %>
    <%= f.number_field :preparation_time, step: '0.25', value: 0.25, min: 0.25, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= f.label :cooking_time, class: 'form-label' %>
    <%= f.number_field :cooking_time, step: '0.25', value: 0.25, min: 0.25, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= f.label :description, class: 'form-label' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= f.label :public, class: 'form-check-label' %>
    <%= f.check_box :public, checked_value: true, unchecked_value: false, class: 'form-check-input' %>
  </div>

  <%= f.submit 'Create a recipe', class: 'btn btn-primary mb-3' %>
<% end %>

app/views/recipes/show.html.erb
<%= render 'layouts/header' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<h2 class= 'header-title'> <%= @recipe.name%> </h2>

<% if can?(:update,@recipe) || @recipe.public  %>
<div class = 'preparation-toggle'> 
<div> <p><strong> Preparation time: <%= @recipe.preparation_time %> <% if @recipe.preparation_time > 1 %> hours <% else %> hour <%end%> </strong> </p> </div>
<div> 
<% if can?(:update, @recipe) %>
  <%= form_with(model: @recipe, url: toggle_public_recipe_path(@recipe), method: :patch) do |form| %>
    <% if @recipe.public %>
      <%= form.submit 'Make Private', class: 'btn btn-danger' %>
    <% else %>
      <%= form.submit 'Make Public', class: 'btn btn-primary' %>
    <% end %>
  <% end %>
<% end %>

</div>
</div>
<div class = 'preparation'>
<p> <strong> Cooking time: <%= @recipe.cooking_time %> <% if @recipe.cooking_time > 1 %> hours <% else %> hour <%end%> </strong></p>
</div>
<div class = 'prep-tion'>
<p><strong> Recipe steps:</strong> <%= @recipe.description %>  </p>
</div>


 <div class="preparation-toggle ">
<%= button_to "Generate shopping list", general_shopping_lists_path, method: :get, class: "btn btn-primary generator " %>
<% if can?(:update, @recipe)%>
<%= button_to "Add Ingredient", new_recipe_recipe_food_path(@recipe), method: :get, class: "btn btn-primary generator" %>
<%end%>
</div> 


<table class="table table-bordered table-striped">
<thead>
<tr>
<th> Food </th>
<th> Quantity </th>
<th> Value </th>
<th> Actions </th>
 </tr>
 </thead>
 <tbody>
 <%@recipe.recipe_foods.each do |recipe_food|%> 
 <tr>
  <td> <%= recipe_food.food.name %> </td>
   <td><%="#{recipe_food.quantity} #{recipe_food.food.measurement_unit}"%></td>
    <td><%= recipe_food.quantity * recipe_food.food.price %>$</td>
    <%if can?(:update,@recipe)%>
    
    <td class='meta-k'>
    <div class="button-group">
    <%= button_to 'Delete',recipe_recipe_food_path(@recipe,recipe_food),method: :delete, class: 'btn btn-danger' %>
    <button class='btn btn-success'>Modify 
    </div>
    </td>

    <%end%>
  </tr>

 <%end%>
 </tbody>

<table>
<%else%>
<h2 class='header-title'> This recipe is private </h2>
<%end%>