config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]

  resources :foods, except: [:update]
  resources :recipes, except: [:update] do
    resources :foods, only: [:new, :create, :destroy]
    resources :recipe_foods, only: [:new, :create, :destroy]
    patch 'toggle_public', on: :member
  end

  resources :public_recipes, except: [:update]

  resources :general_shopping_lists, only: [:index]

  root 'public_recipes#index'
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'food_id'
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods.order("#{sort_column} #{sort_direction}")
  end

  def new
    @food = current_user.foods.build
  end

  def create
    @food = current_user.foods.build(food_params)

    if @food.save
      redirect_to foods_path, notice: 'Food was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @food = current_user.foods.find(params[:id])
    @food.destroy

    redirect_to foods_path, notice: 'Food was successfully destroyed.'
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end

  def sortable_columns
    %w[name measurement_unit price quantity]
  end

  def sort_column
    sortable_columns.include?(params[:sort]) ? params[:sort] : 'name'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/create.html.erb
<h1 class="food_name">Foods#create</h1>
<p>Find me in app/views/foods/create.html.erb</p>

app/views/foods/destroy.html.erb
<h1 class="food_name">Foods#destroy</h1>
<p>Find me in app/views/foods/destroy.html.erb</p>

app/views/foods/edit.html.erb
<h1 class="food_name">Foods#edit</h1>
<p>Find me in app/views/foods/edit.html.erb</p>

app/views/foods/index.html.erb
<%= render 'layouts/header' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<h1 class="food_name">Food List</h1>

<p><%= link_to 'Add Food', new_food_path, class: "btn_new_food" %></p>

<table id="foods">
  <thead class="love">
    <tr class="love">
      <th class="love"><%= sortable 'name' %></th>
      <th class="love"><%= sortable 'measurement_unit' %></th>
      <th class="love"><%= sortable 'price' %></th>
      <th class="love"><%= sortable 'quantity' %></th>
      <th class="love">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <tr class="ken">
        <td><%= food.name %></td>
        <td><%= food.measurement_unit %></td>
        <td><%= number_to_currency(food.price) %></td>
        <td><%= food.quantity %></td>
        <td>
          <%= button_to 'DELETE', food_path(food), method: :delete, class: "btn_delete" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/foods/new.html.erb
<h1 class="food_name">Add Food</h1>

<%= form_with(model: @food, url: foods_path) do |form| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% @food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="table_unit">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="table_unit">
    <%= form.label :measurement_unit %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div class="table_unit">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="table_unit">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div class="table_unit">
    <%= form.submit 'Create Food' %>
  </div>
<% end %>

app/views/foods/show.html.erb
<h1 class="food_name">Foods#show</h1>
<p>Find me in app/views/foods/show.html.erb</p>