config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]

  resources :foods, except: [:update]
  resources :recipes, except: [:update] do
    resources :foods, only: [:new, :create, :destroy]
    resources :recipe_foods, only: [:new, :create, :destroy]
    patch 'toggle_public', on: :member
  end

  resources :public_recipes, except: [:update]

  resources :general_shopping_lists, only: [:index]

  root 'public_recipes#index'
end

app/views/layouts/_header.html.erb
<div class="center-container">
<p class="nav_name">Hello <%= current_user.name%></p>
<nav>
  <div class="menu">
    <div class="mobile-menu-toggle">&#9776;</div>
    <ul class="menu-items">
    <li><%= link_to 'Foods', foods_path, class: "nav-item" %></li>
      <li><%= link_to 'Recipes', recipes_path, class: "nav-item" %></li>
      <li><%= link_to 'Public Recipes', public_recipes_path, class: "nav-item" %></li>
      <li><%= link_to 'General Shopping List', general_shopping_lists_path, class: "nav-item" %></li>
      <li>
        <% if user_signed_in? %>
          <div class="sign_out">
          </div>
        <% else %>
          <%= button_to "Sign In", new_user_session_path, class: "nav-btn" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

<!-- JavaScript code to toggle menu items -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
  $('.mobile-menu-toggle').click(function() {
    $('.menu-items').toggleClass('show');
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorGroupProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <header>
      <%= render 'layouts/header' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </header>
    <p>hello</p>
  </body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml">

   <head>
      <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
      <meta http-equiv = "Content-Language" content = "en-us" />
      <title>Library Info System</title>
      <%= stylesheet_link_tag "application" %>
      <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
       <!-- Other meta tags and stylesheets -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
   </head>

   <body id = "library">
      <div id = "container">
         
       <header id="header">
  <% if user_signed_in? %>
    <%= link_to "Sign Out", destroy_user_session_path%>
  <% else %>
    <%= link_to "Sign In", new_user_session_path %>
    <%= link_to "Sign Up", new_user_registration_path %>
  <% end %>
</header>

         <div id = "content">
            <%= yield -%>
         </div>
         
      </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
   </body>
   
</html>